# Generated by Django 3.2.4 on 2021-06-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Busy')], default='Free', max_length=1),
        ),
    ]
