# Generated by Django 3.2.4 on 2021-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_team_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Busy')], default='F', max_length=1),
        ),
    ]
