# Generated by Django 3.2.4 on 2021-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_team_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.CharField(choices=[('Free', 'Free'), ('Busy', 'Busy')], default='F', max_length=4),
        ),
    ]
