# Generated by Django 3.2.4 on 2021-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210701_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='endLat',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='team',
            name='endLong',
            field=models.CharField(default='', max_length=6),
        ),
    ]
