# Generated by Django 3.2.4 on 2021-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210824_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='endLat',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='endLong',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
