# Generated by Django 3.2.4 on 2021-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210824_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='endLat',
            field=models.DecimalField(blank=True, decimal_places=6, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='endLong',
            field=models.DecimalField(blank=True, decimal_places=6, default='', max_digits=10),
        ),
    ]
