# Generated by Django 3.2.4 on 2021-08-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210824_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='endLat',
            field=models.DecimalField(blank=True, decimal_places=30, default=0.0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='endLong',
            field=models.DecimalField(blank=True, decimal_places=30, default=0.0, max_digits=40),
        ),
    ]
