# Generated by Django 3.2.4 on 2021-09-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210824_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lat',
            field=models.DecimalField(decimal_places=30, default=0.0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='long',
            field=models.DecimalField(decimal_places=30, default=0.0, max_digits=40),
        ),
    ]
