# Generated by Django 3.2.4 on 2021-10-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20211005_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
