# Generated by Django 3.2.4 on 2021-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_delete_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('ONGOING', 'ONGOING'), ('PAST', 'PAST')], default='d', max_length=7)),
                ('lat', models.DecimalField(blank=True, decimal_places=30, max_digits=40)),
                ('long', models.DecimalField(blank=True, decimal_places=30, max_digits=40)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
