# Generated by Django 3.2.4 on 2021-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_case_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
