# Generated by Django 3.2.4 on 2021-10-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_case_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='team',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='backend.team'),
        ),
    ]
