# Generated by Django 3.2.4 on 2021-10-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_case_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='surname',
        ),
        migrations.AddField(
            model_name='case',
            name='extra_information',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
