# Generated by Django 3.2.4 on 2021-10-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20211005_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='token',
            field=models.CharField(default='token', max_length=200),
        ),
    ]
