# Generated by Django 3.2.4 on 2021-11-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20211103_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='extra_information',
            new_name='extraInformation',
        ),
    ]
