# Generated by Django 3.2.4 on 2021-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_rename_extra_information_case_extrainformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='state',
            field=models.CharField(choices=[('TOACCEPT', 'TOACCEPT'), ('ONGOING', 'ONGOING'), ('PAST', 'PAST')], default='default', max_length=8),
        ),
    ]
