# Generated by Django 3.2.4 on 2021-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_case_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10),
        ),
    ]
