# Generated by Django 3.2.4 on 2021-12-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_case_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='isPatient',
            field=models.BooleanField(default=False),
        ),
    ]
